name: Linting and Formatting
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
=======
      - uses: actions/checkout@v2
>>>>>>> 67eae0b (specify node version in github action)
        with:
          node-version: '16'
      - name: Install packages
        run: npm ci
      - name: Run Prettier
        run: prettier --write
      - name: Run ESLint
        run: eslint --fix
