name: Linting and Formatting
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Prettier
        run: prettier --write
      - name: Run ESLint
        run: eslint --fix
